openapi: 3.0.0
servers:
  - description: A dev server endpoint
    url: http://192.168.1.84/cg/gateway/registry
info:
  version: "1.0.0"
  title: cg-gateway-registration-api
  description: |
    Device registration gateway API. Allows a remote device to register itself
    with the gateway or update its status.
paths:
  "/devices/status/{deviceId}":
    get:
      tags:
        - registry
          device
          status
      description: Returns registered devices status info
      operationId: callGetDeviceStatus
      responses:
        "200":
          description: Registered device status info
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/DeviceCurrentStateType"
              examples:
                deviceCurrentStateTypeExample:
                  $ref: "#/components/examples/DeviceCurrentStateTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
    put:
      tags:
        - registry
          device
          status
      description: Update device status
      operationId: updateDeviceStatus
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: Device status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceCurrentStateType"
              examples:
                deviceCurrentStateTypeExample:
                  $ref: "#/components/examples/DeviceCurrentStateTypeExample"
        "500":
          description: Internal device error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceCurrentStateType"
            examples:
              deviceCurrentStateTypeExample:
                $ref: "#/components/examples/DeviceCurrentStateTypeExample"
  "/devices":
    get:
      tags:
        - registry
          device
          registration
      description: Returns the list of registered devices
      operationId: callGetOnDeviceList
      responses:
        "200":
          description: The list of registered devices is successfully returned
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeviceRegistrationType"
              examples:
                deviceRegistrationTypesExample:
                  $ref: "#/components/examples/DeviceRegistrationTypesExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
    post:
      tags:
        - registry
          device
          registration
      description: Register a new device
      operationId: registerNewDevice
      responses:
        "200":
          description: Device is successfully registered on the gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceRegistrationType"
              examples:
                deviceRegistrationTypeExample:
                  $ref: "#/components/examples/DeviceRegistrationTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRegistrationType"
            examples:
              deviceRegistrationTypeExample:
                $ref: "#/components/examples/DeviceRegistrationTypeExample"
  "/devices/{deviceId}":
    get:
      tags:
        - registry
          device
          registration
      description: Returns a registered device registration info
      operationId: callGetOnDevice
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: A registered devices registration info
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeviceRegistrationType"
              examples:
                deviceRegistrationTypeExample:
                  $ref: "#/components/examples/DeviceRegistrationTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
    put:
      tags:
        - registry
          device
          registration
      description: Update a registered device registration info
      operationId: updateExistingDeviceRegistrationInfo
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: Device info is successfully updated in the gateway configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceRegistrationType"
              examples:
                deviceRegistrationTypeExample:
                  $ref: "#/components/examples/DeviceRegistrationTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRegistrationType"
            examples:
              deviceRegistrationTypeExample:
                $ref: "#/components/examples/DeviceRegistrationTypeExample"
    delete:
      tags:
        - registry
          device
          registration
      description: Delete a registered device
      operationId: deleteDevice
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
      responses:
        "200":
          description: Device info is successfully deleted from the gateway configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceRegistrationType"
              examples:
                deviceRegistrationTypeExample:
                  $ref: "#/components/examples/DeviceRegistrationTypeExample"
        "400":
          description: Request message validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorValidationExample:
                  $ref: "#/components/examples/ErrorValidationExample"
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRegistrationType"
            examples:
              deviceStateUpdateTypeExample:
                $ref: "#/components/examples/DeviceRegistrationTypeExample"

  "/devices/{deviceId}/{deviceResource}":
    get:
      tags:
        - gateway
          device resources
      description: Calls GET on a device resource
      operationId: callGetOnDeviceResource
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
        - in: path
          name: deviceResource
          description: Device resource without leading '/'
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Device resource response content
          content:
            "*/*":
              schema:
                type: string
                format: binary
        "500":
          description: Internal gateway error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
        "503":
          description: Device resource call error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithDeviceErrorInfo"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorWithDeviceErrorInfoExample"
    post:
      tags:
        - gateway
          device resources
      description: Calls POST on a device resource
      operationId: callPostOnDeviceResource
      parameters:
        - in: path
          name: deviceId
          description: Device unique identifier
          schema:
            $ref: "#/components/schemas/DeviceIdType"
          examples:
            deviceIdTypeExample:
              $ref: "#/components/examples/DeviceIdTypeExample"
          required: true
        - in: path
          name: deviceResource
          description: Device resource without leading '/'
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successfully called POST on a device resource
          content:
            "*/*":
              schema:
                type: string
                format: binary
                description: Device resource response message body
        "500":
          description: Internal device error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorInternalExample"
        "503":
          description: Device resource call error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorWithDeviceErrorInfo"
              examples:
                errorInternalExample:
                  $ref: "#/components/examples/ErrorWithDeviceErrorInfoExample"
      requestBody:
        content:
          "*/*":
            schema:
              type: string
              format: binary
              description: Device resource request message body
components:
  schemas:
    DeviceIdType:
      type: string
      description: Device unique identifier
      maxLength: 4
      example: "0001"
    DeviceStateType:
      type: string
      enum:
        - active
        - sleeping
        - stopped
        - error
      description: Device possible states
      example: "active"
    DeviceCurrentStateType:
      type: object
      description: Current device state
      properties:
        deviceId:
          $ref: "#/components/schemas/DeviceIdType"
        deviceState:
          $ref: "#/components/schemas/DeviceStateType"
    DeviceRegistrationType:
      type: object
      description: The device registration data
      properties:
        deviceType:
          type: string
          description: Device type description
          example: "switch"
        deviceId:
          type: string
          maxLength: 4
          description: Device unique identifier
          example: "0001"
        deviceTags:
          type: array
          description: Device description tags
          items:
            type: string
            description: Single device description tag
            example: "SRD-05VDC-SL-C"
        deviceUri:
          type: string
          format: uri
          description: Device base URI
          example: "http://192.168.1.84/cg/actuator/switch/0001"
        statusUpdatePeriod:
          type: integer
          minimum: 0
          description: Device status maximum update time interval on the gateway in milliseconds
          example: 600000
    Error:
      type: object
      description: Gateway common error type
      properties:
        errorCode:
          description: Unique error code
          type: string
          maxLength: 4
        errorMsg:
          description: Detailed error description
          type: string
    ErrorWithDeviceErrorInfo:
      type: object
      description: Gateway error type with device original error description
      properties:
        errorCode:
          description: Unique error code
          type: string
          maxLength: 4
        errorMsg:
          description: Detailed error description
          type: string
        deviceResponseHttpCode:
          description: Device response original HTTP code
          type: integer
        deviceErrorCode:
          description: Device original error code
          type: string
          maxLength: 4
        deviceErrorMsg:
          description: Device original error description
          type: string
  examples:
    DeviceIdTypeExample:
      value: "0001"
    DeviceCurrentStateTypeExample:
      value:
        deviceId: "0001"
        deviceState: "active"
    DeviceRegistrationTypeExample:
      value:
        deviceType: "switch"
        deviceId: "0001"
        deviceTags:
          - "SRD-05VDC-SL-C"
        deviceUri: "http://192.168.1.84/cg/actuator/switch/0001"
        statusUpdatePeriod: 600000
    DeviceRegistrationTypesExample:
      value:
        - deviceType: "switch"
          deviceId: "0001"
          deviceTags:
            - "SRD-05VDC-SL-C"
          deviceUri: "http://192.168.1.84/cg/actuator/switch/0001"
          statusUpdatePeriod: 600000
        - deviceType: "switch"
          deviceId: "0002"
          deviceTags:
            - "SRD-05VDC-SL-C"
          deviceUri: "http://192.168.1.84/cg/actuator/switch/0002"
          statusUpdatePeriod: 10000
    DeviceResourceExample:
      value: "state"
      description: |
        state - is a name of the device resource where complete URL
        can look as http://192.168.1.84/cg/actuator/switch/0001/state
    ErrorValidationExample:
      value:
        errorCode: "0001"
        errorMsg: "InvalidInput"
    ErrorInternalExample:
      value:
        errorCode: "0002"
        errorMsg: "Internal gateway error"
    ErrorUnableToRegisterExample:
      value:
        errorCode: "0003"
        errorMsg: "Device registration error"
    ErrorWithDeviceErrorInfoExample:
      value:
        errorCode: "0004"
        errorMsg: "Unable to call device resource"
        deviceResponseHttpCode: 500
        deviceErrorCode: "0001"
        deviceErrorMsg: "Internal device error"